### ISSUE TITLE
Requirements for NumFocus Fiscal Sponsorship

### ISSUE THREAD

**Issue by jcrist** [dask/governance#1]
We may want to apply for NumFocus Fiscal Sponsorship: https://numfocus.org/information-fiscal-sponsorship

The requirements are:

- [x] Release its code under an OSI approved open source license (exceptions must be approved by the NumFOCUS Board of Directors)
- [x] Have a Code of Conduct, either adopted from our own or similar in spirit.
- [x] Have a community that is active and of reasonable size
- [x] Have multiple people willing to sign the Fiscal Sponsorship Agreement (5 signatories for a comprehensive FSA; 3 signatories for a grantor-grantee FSA). Those people must be active in the project; one person may be an external stakeholder instead of a project contributor.​
- [x] Have a leadership body or team consisting of at least 3 people; these people should not be employed by the same entity or share a common affiliation beyond that of the project.

**Comment by mrocklin** [comment]
I've switched the itemized list above into a checklist.

**Comment by mrocklin** [comment]
> 5 signatories for a comprehensive FSA

I propose the following:

-  Matthew Rocklin
-  Jim Crist
-  Stephan Hoyer
-  James Bourbeau
-  ??? one more?

I targetted first different institutions.   I think I'd also like to target different domains.  If Stephan represents array computing / xarray, it would be good to have a dataframes/ML person.

**Comment by jakirkham** [comment]
Combing through the discussions here @ogrisel, @pitrou, and @guillaumeeb have all been pretty engaged in the governance process (so potentially interested?). They are all from different institutions than those listed. Also they are involved in different parts of Dask that don't overlap with the expertise in the current group. Not trying to volunteer any of them for the role should they not want it, but if they are interested they would all be strong candidates in my mind.

**Comment by guillaumeeb** [comment]
This is nice to think of me @jakirkham, but I don't think I really qualified for this, in term of availability, general daask knowledge, and nationality!

**Comment by jcrist** [comment]
>  I think I'd also like to target different domains. If Stephan represents array computing / xarray, it would be good to have a dataframes/ML person.

If you're not opposed to having multiple people from one institution, I'll also nominate @TomAugspurger as someone who would fit this role.

**Comment by TomAugspurger** [comment]
I'm happy to join on if needed.

**Comment by jakirkham** [comment]
How do we proceed?

Thus far it sounds like our requirements for the 5th person may be too strict. Would we be comfortable relaxing them?

Alternatively it may be people are not comfortable stepping up as they don't know what is expected of them. Could we enumerate the expectations of the signatories so people that may be quietly watching from the sidelines have a better idea of what they would be signing up for (assuming they step forward and volunteer ;)?

**Comment by mrocklin** [comment]
I think that Tom would be a fine choice.  He's been around in the project for a long time, participates in a variety of other OSS projects, and I get the sense that he is fairly well trusted by the broader community.

> Alternatively it may be people are not comfortable stepping up as they don't know what is expected of them. Could we enumerate the expectations of the signatories so people that may be quietly watching from the sidelines have a better idea of what they would be signing up for (assuming they step forward and volunteer ;)?

No objection from me.

**Comment by jakirkham** [comment]
I'm also happy to go with Tom. This would mean that we have 2 FSAs from the same org. Not sure if there are implications to that.

Should add I don't know offhand what the expectations of FSAs are. If someone who does wants to fill those out, that would be great. I'd also be just fine sticking with the forming consensus around choosing Tom as the 5th FSA.

As to the last item on the leadership team, what is needed for that? Completing the governance doc? Something else in discussion? Or is there something we have not yet discussed here?

**Comment by mrocklin** [comment]
> I'm also happy to go with Tom. This would mean that we have 2 FSAs from the same org. Not sure if there are implications to that.

I suspect that it's fine

> Should add I don't know offhand what the expectations of FSAs are. If someone who does wants to fill those out, that would be great. I'd also be just fine sticking with the forming consensus around choosing Tom as the 5th FSA.

I don't know what they are in particular and no one else has chimed in.  I suggest that we just go with the following list:

-  Matthew Rocklin
- Jim Crist
- Stephan Hoyer
- James Bourbeau
- Tom Augspurger

> As to the last item on the leadership team, what is needed for that? Completing the governance doc? Something else in discussion? Or is there something we have not yet discussed here?

I think so?  At this point I think that we should just apply and see if they ask for something in particular.

**Comment by jakirkham** [comment]
@shoyer and @jrbourbeau, are you happy to be FSAs?

(Realized you might not have noticed this thread)

**Comment by jakirkham** [comment]
Also @aterrel would you be able to clarify what the obligations of FSAs are (as we don't seem to know)?

**Comment by jrbourbeau** [comment]
Yes, I'm happy to be a signatory on the FSA

**Comment by shoyer** [comment]
Sure, happy to be a signatory.

**Comment by aterrel** [comment]
@jakirkham what kind of obligations are you referring? might be better to have a call with Leah and I to go through different processes and things we do together. For example, you can't use the project to promote a political candidate in the US, there is a monthly newsletter that we ask for input on. but usually we don't require anything specifically from Dask

**Comment by jakirkham** [comment]
Sorry for being unclear @aterrel. What I meant was, are there particular things required of the people who sign the FSA? Are there meetings they should be attending? Particular tasks that they should be completing throughout the year? It sounds like the answer may be no, which is fine. Just trying to ensure both the people that sign the FSA and the rest of us know what they are signing up for. 🙂

**Comment by aterrel** [comment]
Well in general those people are the ones who are responsible for ensuring the project uses its fiscal status in a way keeping with the non-profit nature of the project. So we put you on a list and are the folks we send things like funding approval and contract negotiations with. For most projects it's pretty minimal but if you do take on large grants or other complex financial instrument it could be more work. "Choose your level of fun" =P

For NumFOCUS we want the group that can make authoritative decisions without having to manage a large discussion on community mailing lists for any decision.

**Comment by jakirkham** [comment]
Thanks Andy. That answers my question. Let's see if others have any more questions.

**Comment by martindurant** [comment]
Suggest the silence means "no more questions"

**Comment by mrocklin** [comment]
I've filled out the NumFOCUS form here: https://docs.google.com/document/d/1jkHlVE02NWCqj3f317CqG_jTFqlQfqjWj0zVtP2qy_E/edit?usp=sharing

I plan to submit it it tomorrow if there are no concerns.  Given that this isn't as binding as the governance or code-of-conduct documents, I'd like to avoid lots of back-and-forth on this doc if possible.  If people have serious concerns though, please do let me know.  I believe that the purpose of this document is to convince the NumFOCUS board that they should accept Dask as a project within NumFOCUS.  I believe that this is an easy argument to make, and so doesn't require a ton of fine-tuning on our end.

**Comment by jrbourbeau** [comment]
Thank you for filling out the form @mrocklin, it looks good and I have no serious concerns. 

FWIW I caught one typo in Section 2a: "Dask helps make make of"

**Comment by jakirkham** [comment]
No concerns. LGTM. Thanks for doing this.

**Comment by mrocklin** [comment]
Submitted.  Received ACK e-mail.

**Comment by jrbourbeau** [comment]
Closing as Dask is officially a NumFOCUS fiscally sponsored project 🎉 

Thanks all for your work on this!
