### ISSUE TITLE
Create private mailing list for the steering committee

### ISSUE THREAD

**Issue by mrocklin** [dask/governance#14]
We should probably make a mailing list for private communication among the steering committee.  I think that for public communications we can possibly use a github issue tracker, but for private communications e-mail would be useful.  I often find myself sending out an e-mail to a bunch of individual e-mail addresses.

**Comment by TomAugspurger** [comment]
@jrbourbeau set up a private google group for the CoC committee.

**Comment by jakirkham** [comment]
A private Google Group sounds good. Have used similar for other private mailing lists before and it seems to work well.

**Comment by jrbourbeau** [comment]
Great, I'll set up a group for the steering committee then

**Comment by jakirkham** [comment]
Thanks for taking this on 🙂

**Comment by jrbourbeau** [comment]
Just sent out invites to the steering committee (current set of dask org owners)
