### ISSUE TITLE
How should we develop a governance model?

### ISSUE THREAD

**Issue by jcrist** [dask/governance#2]
How do we go about creating governance model? A few options:

- Adopt (and modify) one from an existing project? A few examples:
  - Jupyter: https://github.com/jupyter/governance
  - Pangeo: https://github.com/pangeo-data/governance
  - Pandas: https://github.com/pandas-dev/pandas-governance
  - Django: https://docs.djangoproject.com/en/dev/internals/organization/
- Develop a fresh document?
- ?

**Comment by jakirkham** [comment]
Maybe not too relevant at this stage of the discussion, but I rather enjoyed reading [this overview of governance models]( http://oss-watch.ac.uk/resources/governancemodels ).
