### ISSUE TITLE
Managing commit/org access rights

### ISSUE THREAD

**Issue by jcrist** [dask/governance#7]
How do we manage commit/org access rights? This includes things like:

- Adding new projects to the dask org
- Giving someone commit access to a project
- Giving someone access to the organization
- Removing commit access (either no longer active, or disciplinary (hopefully never needed))

Currently we have a fairly liberal (give access early and often) and informal process, but we'll want to codify this as part of the governance model.

**Comment by mrocklin** [comment]
Our current policy was discussed at length in https://github.com/dask/dask/issues/3223

And in particular in https://github.com/dask/dask/issues/3223#issuecomment-371475223

My thoughts on this policy over the last few months:
-  Despite being liberal, I think that I'm the only one who has pushed to add someone to a repository or the organization.  So perhaps it is not easy enough?  (or maybe this is cultural, where others don't feel comfortable making these moves)
-  We haven't had any negative effects from adding people
-  We might want to give more permissions to people if possible.  For example members aren't able to close issues currently if they aren't also committers.

**Comment by mrocklin** [comment]
we copied in the github conversation to a document in #12
